names<-c("siri","mahi","chiru")
age<-c(23,24,25)
marks<-c(88,78,25)
df<-data.frame(names,age,marks)
mean(df $age)
write.csv(df,"datafr.csv")
median(df $age)
write.csv(df,"datafr.csv")
mode(df $age)
write.csv(df,"datafr.csv")
̥
